<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerFastModeProjectMountDirectory>/home/site/wwwroot</DockerFastModeProjectMountDirectory>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<UserSecretsId>Genocs</UserSecretsId>
        <PackageId>Genocs.DocumentImporter</PackageId>
        <RootNamespace>Genocs.DocumentImporter</RootNamespace>
        <AssemblyName>Genocs.DocumentImporter</AssemblyName>
        <Title>Genocs Azure AI Document Importer</Title>
        <Description>Import document through Azure AI Foundry.</Description>
        <Summary>A set of Azure Function to import external cocuments into CosmosDB database.</Summary>
        <PackageTags>genocs azure foundry cosmosdb</PackageTags>		
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		
		<PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
		<PackageReference Include="Azure.Storage.Files.Shares" Version="12.27.1" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />

		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.51.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.8.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.16.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
		<PackageReference Include="Microsoft.Extensions.Azure" Version="1.14.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />

		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Azure.AI.ContentUnderstanding" Version="1.1.0" />

		<PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
		<PackageReference Include="Azure.AI.DocumentIntelligence" Version="1.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />

	</ItemGroup>

</Project>
